Fix unwanted indentation
tue-robotics/dynamixel_motor pull request #2
Opened 2018-05-01 19:20 UTC by MatthijsBurgh

This was not in the original driver. This is an inaccuracy.

2018-05-01 23:18 UTC, MatthijsBurgh commented
@rokusottervanger, already reviewed at the German Open. I thought I applied his review, but I was missed.

2018-06-06 20:08 UTC, MatthijsBurgh commented
ping

2018-06-11 19:42 UTC, rokusottervanger commented
I don't remember reviewing this on RGO. See my comment.

2018-06-11 19:43 UTC, rokusottervanger requested changes

2018-06-11 19:43 UTC, rokusottervanger commented on dynamixel_driver/src/dynamixel_driver/dynamixel_io.py
> +        return data
Looks like data might be referenced before assignment. What does your IDE say?

2018-06-11 19:43 UTC, rokusottervanger commented
Since the only change here introduces a bug, I'm closing this PR.

2018-06-11 19:43 UTC, closed without merging